// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutService.proto

package via.sep3.logicserver.protobuf;

public interface AssignWorkoutObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AssignWorkoutObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userID = 1;</code>
   * @return The userID.
   */
  int getUserID();

  /**
   * <code>int32 workoutID = 2;</code>
   * @return The workoutID.
   */
  int getWorkoutID();
}
