// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

public interface EmptyParOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmptyPar)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string empty = 1;</code>
   * @return The empty.
   */
  java.lang.String getEmpty();
  /**
   * <code>string empty = 1;</code>
   * @return The bytes for empty.
   */
  com.google.protobuf.ByteString
      getEmptyBytes();
}
