// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

public interface ExercisesInWorkoutsObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExercisesInWorkoutsObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ExerciseId = 1;</code>
   * @return The exerciseId.
   */
  int getExerciseId();

  /**
   * <code>int32 WorkoutId = 2;</code>
   * @return The workoutId.
   */
  int getWorkoutId();
}
