// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

/**
 * Protobuf type {@code ExercisesInWorkoutsObj}
 */
public final class ExercisesInWorkoutsObj extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ExercisesInWorkoutsObj)
    ExercisesInWorkoutsObjOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExercisesInWorkoutsObj.newBuilder() to construct.
  private ExercisesInWorkoutsObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExercisesInWorkoutsObj() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExercisesInWorkoutsObj();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExercisesInWorkoutsObj(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            exerciseId_ = input.readInt32();
            break;
          }
          case 16: {

            workoutId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.logicserver.protobuf.LogicServer.internal_static_ExercisesInWorkoutsObj_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.logicserver.protobuf.LogicServer.internal_static_ExercisesInWorkoutsObj_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj.class, via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj.Builder.class);
  }

  public static final int EXERCISEID_FIELD_NUMBER = 1;
  private int exerciseId_;
  /**
   * <code>int32 ExerciseId = 1;</code>
   * @return The exerciseId.
   */
  @java.lang.Override
  public int getExerciseId() {
    return exerciseId_;
  }

  public static final int WORKOUTID_FIELD_NUMBER = 2;
  private int workoutId_;
  /**
   * <code>int32 WorkoutId = 2;</code>
   * @return The workoutId.
   */
  @java.lang.Override
  public int getWorkoutId() {
    return workoutId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (exerciseId_ != 0) {
      output.writeInt32(1, exerciseId_);
    }
    if (workoutId_ != 0) {
      output.writeInt32(2, workoutId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (exerciseId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, exerciseId_);
    }
    if (workoutId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, workoutId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj)) {
      return super.equals(obj);
    }
    via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj other = (via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj) obj;

    if (getExerciseId()
        != other.getExerciseId()) return false;
    if (getWorkoutId()
        != other.getWorkoutId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXERCISEID_FIELD_NUMBER;
    hash = (53 * hash) + getExerciseId();
    hash = (37 * hash) + WORKOUTID_FIELD_NUMBER;
    hash = (53 * hash) + getWorkoutId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ExercisesInWorkoutsObj}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ExercisesInWorkoutsObj)
      via.sep3.logicserver.protobuf.ExercisesInWorkoutsObjOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.logicserver.protobuf.LogicServer.internal_static_ExercisesInWorkoutsObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.logicserver.protobuf.LogicServer.internal_static_ExercisesInWorkoutsObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj.class, via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj.Builder.class);
    }

    // Construct using via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      exerciseId_ = 0;

      workoutId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.logicserver.protobuf.LogicServer.internal_static_ExercisesInWorkoutsObj_descriptor;
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj getDefaultInstanceForType() {
      return via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj build() {
      via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj buildPartial() {
      via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj result = new via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj(this);
      result.exerciseId_ = exerciseId_;
      result.workoutId_ = workoutId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj) {
        return mergeFrom((via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj other) {
      if (other == via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj.getDefaultInstance()) return this;
      if (other.getExerciseId() != 0) {
        setExerciseId(other.getExerciseId());
      }
      if (other.getWorkoutId() != 0) {
        setWorkoutId(other.getWorkoutId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int exerciseId_ ;
    /**
     * <code>int32 ExerciseId = 1;</code>
     * @return The exerciseId.
     */
    @java.lang.Override
    public int getExerciseId() {
      return exerciseId_;
    }
    /**
     * <code>int32 ExerciseId = 1;</code>
     * @param value The exerciseId to set.
     * @return This builder for chaining.
     */
    public Builder setExerciseId(int value) {
      
      exerciseId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ExerciseId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExerciseId() {
      
      exerciseId_ = 0;
      onChanged();
      return this;
    }

    private int workoutId_ ;
    /**
     * <code>int32 WorkoutId = 2;</code>
     * @return The workoutId.
     */
    @java.lang.Override
    public int getWorkoutId() {
      return workoutId_;
    }
    /**
     * <code>int32 WorkoutId = 2;</code>
     * @param value The workoutId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkoutId(int value) {
      
      workoutId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 WorkoutId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkoutId() {
      
      workoutId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ExercisesInWorkoutsObj)
  }

  // @@protoc_insertion_point(class_scope:ExercisesInWorkoutsObj)
  private static final via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj();
  }

  public static via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExercisesInWorkoutsObj>
      PARSER = new com.google.protobuf.AbstractParser<ExercisesInWorkoutsObj>() {
    @java.lang.Override
    public ExercisesInWorkoutsObj parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExercisesInWorkoutsObj(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExercisesInWorkoutsObj> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExercisesInWorkoutsObj> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.logicserver.protobuf.ExercisesInWorkoutsObj getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

