// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

public interface ExercisesTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExercisesTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ExerciseTO exercises = 1;</code>
   */
  java.util.List<via.sep3.logicserver.protobuf.ExerciseTO> 
      getExercisesList();
  /**
   * <code>repeated .ExerciseTO exercises = 1;</code>
   */
  via.sep3.logicserver.protobuf.ExerciseTO getExercises(int index);
  /**
   * <code>repeated .ExerciseTO exercises = 1;</code>
   */
  int getExercisesCount();
  /**
   * <code>repeated .ExerciseTO exercises = 1;</code>
   */
  java.util.List<? extends via.sep3.logicserver.protobuf.ExerciseTOOrBuilder> 
      getExercisesOrBuilderList();
  /**
   * <code>repeated .ExerciseTO exercises = 1;</code>
   */
  via.sep3.logicserver.protobuf.ExerciseTOOrBuilder getExercisesOrBuilder(
      int index);
}
