// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExerciseService.proto

package via.sep3.logicserver.protobuf;

public interface ExercisesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Exercises)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  java.util.List<via.sep3.logicserver.protobuf.ExerciseObj> 
      getExercisesList();
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  via.sep3.logicserver.protobuf.ExerciseObj getExercises(int index);
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  int getExercisesCount();
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  java.util.List<? extends via.sep3.logicserver.protobuf.ExerciseObjOrBuilder> 
      getExercisesOrBuilderList();
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  via.sep3.logicserver.protobuf.ExerciseObjOrBuilder getExercisesOrBuilder(
      int index);
}
