// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExerciseService.proto

package via.sep3.logicserver.protobuf;

/**
 * Protobuf type {@code Exercises}
 */
public final class Exercises extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Exercises)
    ExercisesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Exercises.newBuilder() to construct.
  private Exercises(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Exercises() {
    exercises_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Exercises();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Exercises(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              exercises_ = new java.util.ArrayList<via.sep3.logicserver.protobuf.ExerciseObj>();
              mutable_bitField0_ |= 0x00000001;
            }
            exercises_.add(
                input.readMessage(via.sep3.logicserver.protobuf.ExerciseObj.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        exercises_ = java.util.Collections.unmodifiableList(exercises_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.logicserver.protobuf.ExerciseServiceOuterClass.internal_static_Exercises_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.logicserver.protobuf.ExerciseServiceOuterClass.internal_static_Exercises_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.logicserver.protobuf.Exercises.class, via.sep3.logicserver.protobuf.Exercises.Builder.class);
  }

  public static final int EXERCISES_FIELD_NUMBER = 1;
  private java.util.List<via.sep3.logicserver.protobuf.ExerciseObj> exercises_;
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.logicserver.protobuf.ExerciseObj> getExercisesList() {
    return exercises_;
  }
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.logicserver.protobuf.ExerciseObjOrBuilder> 
      getExercisesOrBuilderList() {
    return exercises_;
  }
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  @java.lang.Override
  public int getExercisesCount() {
    return exercises_.size();
  }
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  @java.lang.Override
  public via.sep3.logicserver.protobuf.ExerciseObj getExercises(int index) {
    return exercises_.get(index);
  }
  /**
   * <code>repeated .ExerciseObj exercises = 1;</code>
   */
  @java.lang.Override
  public via.sep3.logicserver.protobuf.ExerciseObjOrBuilder getExercisesOrBuilder(
      int index) {
    return exercises_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < exercises_.size(); i++) {
      output.writeMessage(1, exercises_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < exercises_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, exercises_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.logicserver.protobuf.Exercises)) {
      return super.equals(obj);
    }
    via.sep3.logicserver.protobuf.Exercises other = (via.sep3.logicserver.protobuf.Exercises) obj;

    if (!getExercisesList()
        .equals(other.getExercisesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getExercisesCount() > 0) {
      hash = (37 * hash) + EXERCISES_FIELD_NUMBER;
      hash = (53 * hash) + getExercisesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.logicserver.protobuf.Exercises parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.Exercises parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.logicserver.protobuf.Exercises prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Exercises}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Exercises)
      via.sep3.logicserver.protobuf.ExercisesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.logicserver.protobuf.ExerciseServiceOuterClass.internal_static_Exercises_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.logicserver.protobuf.ExerciseServiceOuterClass.internal_static_Exercises_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.logicserver.protobuf.Exercises.class, via.sep3.logicserver.protobuf.Exercises.Builder.class);
    }

    // Construct using via.sep3.logicserver.protobuf.Exercises.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getExercisesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (exercisesBuilder_ == null) {
        exercises_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        exercisesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.logicserver.protobuf.ExerciseServiceOuterClass.internal_static_Exercises_descriptor;
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.Exercises getDefaultInstanceForType() {
      return via.sep3.logicserver.protobuf.Exercises.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.Exercises build() {
      via.sep3.logicserver.protobuf.Exercises result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.Exercises buildPartial() {
      via.sep3.logicserver.protobuf.Exercises result = new via.sep3.logicserver.protobuf.Exercises(this);
      int from_bitField0_ = bitField0_;
      if (exercisesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          exercises_ = java.util.Collections.unmodifiableList(exercises_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.exercises_ = exercises_;
      } else {
        result.exercises_ = exercisesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.logicserver.protobuf.Exercises) {
        return mergeFrom((via.sep3.logicserver.protobuf.Exercises)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.logicserver.protobuf.Exercises other) {
      if (other == via.sep3.logicserver.protobuf.Exercises.getDefaultInstance()) return this;
      if (exercisesBuilder_ == null) {
        if (!other.exercises_.isEmpty()) {
          if (exercises_.isEmpty()) {
            exercises_ = other.exercises_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExercisesIsMutable();
            exercises_.addAll(other.exercises_);
          }
          onChanged();
        }
      } else {
        if (!other.exercises_.isEmpty()) {
          if (exercisesBuilder_.isEmpty()) {
            exercisesBuilder_.dispose();
            exercisesBuilder_ = null;
            exercises_ = other.exercises_;
            bitField0_ = (bitField0_ & ~0x00000001);
            exercisesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExercisesFieldBuilder() : null;
          } else {
            exercisesBuilder_.addAllMessages(other.exercises_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.logicserver.protobuf.Exercises parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.logicserver.protobuf.Exercises) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.logicserver.protobuf.ExerciseObj> exercises_ =
      java.util.Collections.emptyList();
    private void ensureExercisesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        exercises_ = new java.util.ArrayList<via.sep3.logicserver.protobuf.ExerciseObj>(exercises_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.logicserver.protobuf.ExerciseObj, via.sep3.logicserver.protobuf.ExerciseObj.Builder, via.sep3.logicserver.protobuf.ExerciseObjOrBuilder> exercisesBuilder_;

    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public java.util.List<via.sep3.logicserver.protobuf.ExerciseObj> getExercisesList() {
      if (exercisesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(exercises_);
      } else {
        return exercisesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public int getExercisesCount() {
      if (exercisesBuilder_ == null) {
        return exercises_.size();
      } else {
        return exercisesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseObj getExercises(int index) {
      if (exercisesBuilder_ == null) {
        return exercises_.get(index);
      } else {
        return exercisesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder setExercises(
        int index, via.sep3.logicserver.protobuf.ExerciseObj value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.set(index, value);
        onChanged();
      } else {
        exercisesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder setExercises(
        int index, via.sep3.logicserver.protobuf.ExerciseObj.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.set(index, builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder addExercises(via.sep3.logicserver.protobuf.ExerciseObj value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.add(value);
        onChanged();
      } else {
        exercisesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder addExercises(
        int index, via.sep3.logicserver.protobuf.ExerciseObj value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.add(index, value);
        onChanged();
      } else {
        exercisesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder addExercises(
        via.sep3.logicserver.protobuf.ExerciseObj.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.add(builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder addExercises(
        int index, via.sep3.logicserver.protobuf.ExerciseObj.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.add(index, builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder addAllExercises(
        java.lang.Iterable<? extends via.sep3.logicserver.protobuf.ExerciseObj> values) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, exercises_);
        onChanged();
      } else {
        exercisesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder clearExercises() {
      if (exercisesBuilder_ == null) {
        exercises_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        exercisesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public Builder removeExercises(int index) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.remove(index);
        onChanged();
      } else {
        exercisesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseObj.Builder getExercisesBuilder(
        int index) {
      return getExercisesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseObjOrBuilder getExercisesOrBuilder(
        int index) {
      if (exercisesBuilder_ == null) {
        return exercises_.get(index);  } else {
        return exercisesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public java.util.List<? extends via.sep3.logicserver.protobuf.ExerciseObjOrBuilder> 
         getExercisesOrBuilderList() {
      if (exercisesBuilder_ != null) {
        return exercisesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(exercises_);
      }
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseObj.Builder addExercisesBuilder() {
      return getExercisesFieldBuilder().addBuilder(
          via.sep3.logicserver.protobuf.ExerciseObj.getDefaultInstance());
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseObj.Builder addExercisesBuilder(
        int index) {
      return getExercisesFieldBuilder().addBuilder(
          index, via.sep3.logicserver.protobuf.ExerciseObj.getDefaultInstance());
    }
    /**
     * <code>repeated .ExerciseObj exercises = 1;</code>
     */
    public java.util.List<via.sep3.logicserver.protobuf.ExerciseObj.Builder> 
         getExercisesBuilderList() {
      return getExercisesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.logicserver.protobuf.ExerciseObj, via.sep3.logicserver.protobuf.ExerciseObj.Builder, via.sep3.logicserver.protobuf.ExerciseObjOrBuilder> 
        getExercisesFieldBuilder() {
      if (exercisesBuilder_ == null) {
        exercisesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sep3.logicserver.protobuf.ExerciseObj, via.sep3.logicserver.protobuf.ExerciseObj.Builder, via.sep3.logicserver.protobuf.ExerciseObjOrBuilder>(
                exercises_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        exercises_ = null;
      }
      return exercisesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Exercises)
  }

  // @@protoc_insertion_point(class_scope:Exercises)
  private static final via.sep3.logicserver.protobuf.Exercises DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.logicserver.protobuf.Exercises();
  }

  public static via.sep3.logicserver.protobuf.Exercises getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Exercises>
      PARSER = new com.google.protobuf.AbstractParser<Exercises>() {
    @java.lang.Override
    public Exercises parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Exercises(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Exercises> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Exercises> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.logicserver.protobuf.Exercises getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

