// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExerciseService.proto

package via.sep3.logicserver.protobuf;

public final class ExerciseServiceOuterClass {
  private ExerciseServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExerciseObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExerciseObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Exercises_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Exercises_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ExerciseService.proto\032\021LogicServer.pro" +
      "to\"N\n\013ExerciseObj\022\n\n\002Id\030\001 \001(\005\022\014\n\004Name\030\002 " +
      "\001(\t\022\023\n\013Description\030\003 \001(\t\022\020\n\010Duration\030\004 \001" +
      "(\005\",\n\tExercises\022\037\n\texercises\030\001 \003(\0132\014.Exe" +
      "rciseObj2\270\001\n\017ExerciseService\022,\n\016CreateEx" +
      "ercise\022\014.ExerciseObj\032\014.ExerciseObj\022&\n\014Ge" +
      "tExercises\022\n.StringObj\032\n.Exercises\022(\n\014Ed" +
      "itExercise\022\014.ExerciseObj\032\n.StringObj\022%\n\016" +
      "DeleteExercise\022\007.IntObj\032\n.StringObjB!\n\035v" +
      "ia.sep3.logicserver.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          via.sep3.logicserver.protobuf.LogicServer.getDescriptor(),
        });
    internal_static_ExerciseObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExerciseObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExerciseObj_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Duration", });
    internal_static_Exercises_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Exercises_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Exercises_descriptor,
        new java.lang.String[] { "Exercises", });
    via.sep3.logicserver.protobuf.LogicServer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
