// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

public final class LogicServer {
  private LogicServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MemberTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MemberTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExerciseTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExerciseTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMember_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseMember_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021LogicServer.proto\".\n\010MemberTO\022\020\n\010usern" +
      "ame\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"A\n\nExerciseT" +
      "O\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\020\n\010" +
      "duration\030\003 \001(\005\"\"\n\016ResponseMember\022\020\n\010user" +
      "name\030\002 \001(\t2f\n\rMemberService\022*\n\014createMem" +
      "ber\022\t.MemberTO\032\017.ResponseMember\022)\n\013login" +
      "Member\022\t.MemberTO\032\017.ResponseMember2=\n\017Ex" +
      "erciseService\022*\n\016createExercise\022\013.Exerci" +
      "seTO\032\013.ExerciseTOB!\n\035via.sep3.logicserve" +
      "r.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MemberTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MemberTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MemberTO_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_ExerciseTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ExerciseTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExerciseTO_descriptor,
        new java.lang.String[] { "Name", "Description", "Duration", });
    internal_static_ResponseMember_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResponseMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseMember_descriptor,
        new java.lang.String[] { "Username", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
