// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

public final class LogicServer {
  private LogicServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StringObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StringObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExercisesInWorkoutsObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExercisesInWorkoutsObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021LogicServer.proto\"\031\n\tStringObj\022\014\n\004name" +
      "\030\001 \001(\t\"\030\n\006IntObj\022\016\n\006number\030\001 \001(\005\"?\n\026Exer" +
      "cisesInWorkoutsObj\022\022\n\nExerciseId\030\001 \001(\005\022\021" +
      "\n\tWorkoutId\030\002 \001(\005B!\n\035via.sep3.logicserve" +
      "r.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StringObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StringObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StringObj_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_IntObj_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IntObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntObj_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_ExercisesInWorkoutsObj_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ExercisesInWorkoutsObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExercisesInWorkoutsObj_descriptor,
        new java.lang.String[] { "ExerciseId", "WorkoutId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
