// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberService.proto

package via.sep3.logicserver.protobuf;

public final class MemberServiceOuterClass {
  private MemberServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginCreateObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginCreateObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MemberObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MemberObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MemberService.proto\"7\n\021LoginCreateObje" +
      "ct\022\020\n\010Username\030\001 \001(\t\022\020\n\010Password\030\002 \001(\t\"M" +
      "\n\tMemberObj\022\n\n\002Id\030\001 \001(\005\022\020\n\010Username\030\002 \001(" +
      "\t\022\020\n\010Password\030\003 \001(\t\022\020\n\010Position\030\004 \001(\t2n\n" +
      "\rMemberService\022.\n\014createMember\022\022.LoginCr" +
      "eateObject\032\n.MemberObj\022-\n\013loginMember\022\022." +
      "LoginCreateObject\032\n.MemberObjB!\n\035via.sep" +
      "3.logicserver.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LoginCreateObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginCreateObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginCreateObject_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_MemberObj_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MemberObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MemberObj_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Position", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
