// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberService.proto

package via.sep3.logicserver.protobuf;

public interface MemberObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MemberObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 Id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string Username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string Username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>bytes Password = 3;</code>
   * @return The password.
   */
  com.google.protobuf.ByteString getPassword();

  /**
   * <code>bytes Salt = 4;</code>
   * @return The salt.
   */
  com.google.protobuf.ByteString getSalt();

  /**
   * <code>string Position = 5;</code>
   * @return The position.
   */
  java.lang.String getPosition();
  /**
   * <code>string Position = 5;</code>
   * @return The bytes for position.
   */
  com.google.protobuf.ByteString
      getPositionBytes();
}
