// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MemberService.proto

package via.sep3.logicserver.protobuf;

public interface MembersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Members)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .MemberObj members = 1;</code>
   */
  java.util.List<via.sep3.logicserver.protobuf.MemberObj> 
      getMembersList();
  /**
   * <code>repeated .MemberObj members = 1;</code>
   */
  via.sep3.logicserver.protobuf.MemberObj getMembers(int index);
  /**
   * <code>repeated .MemberObj members = 1;</code>
   */
  int getMembersCount();
  /**
   * <code>repeated .MemberObj members = 1;</code>
   */
  java.util.List<? extends via.sep3.logicserver.protobuf.MemberObjOrBuilder> 
      getMembersOrBuilderList();
  /**
   * <code>repeated .MemberObj members = 1;</code>
   */
  via.sep3.logicserver.protobuf.MemberObjOrBuilder getMembersOrBuilder(
      int index);
}
