// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

/**
 * Protobuf type {@code WorkoutO}
 */
public final class WorkoutO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WorkoutO)
    WorkoutOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkoutO.newBuilder() to construct.
  private WorkoutO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkoutO() {
    name_ = "";
    description_ = "";
    exercises_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorkoutO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WorkoutO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 16: {

            id_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 40: {

            durationInMin_ = input.readInt32();
            break;
          }
          case 48: {

            createdBy_ = input.readInt32();
            break;
          }
          case 56: {

            followedBy_ = input.readInt32();
            break;
          }
          case 64: {

            isPublic_ = input.readBool();
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              exercises_ = new java.util.ArrayList<via.sep3.logicserver.protobuf.ExerciseO>();
              mutable_bitField0_ |= 0x00000001;
            }
            exercises_.add(
                input.readMessage(via.sep3.logicserver.protobuf.ExerciseO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        exercises_ = java.util.Collections.unmodifiableList(exercises_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.logicserver.protobuf.WorkoutO.class, via.sep3.logicserver.protobuf.WorkoutO.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;
  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATIONINMIN_FIELD_NUMBER = 5;
  private int durationInMin_;
  /**
   * <code>int32 durationInMin = 5;</code>
   * @return The durationInMin.
   */
  @java.lang.Override
  public int getDurationInMin() {
    return durationInMin_;
  }

  public static final int CREATEDBY_FIELD_NUMBER = 6;
  private int createdBy_;
  /**
   * <code>int32 createdBy = 6;</code>
   * @return The createdBy.
   */
  @java.lang.Override
  public int getCreatedBy() {
    return createdBy_;
  }

  public static final int FOLLOWEDBY_FIELD_NUMBER = 7;
  private int followedBy_;
  /**
   * <code>int32 followedBy = 7;</code>
   * @return The followedBy.
   */
  @java.lang.Override
  public int getFollowedBy() {
    return followedBy_;
  }

  public static final int ISPUBLIC_FIELD_NUMBER = 8;
  private boolean isPublic_;
  /**
   * <code>bool isPublic = 8;</code>
   * @return The isPublic.
   */
  @java.lang.Override
  public boolean getIsPublic() {
    return isPublic_;
  }

  public static final int EXERCISES_FIELD_NUMBER = 9;
  private java.util.List<via.sep3.logicserver.protobuf.ExerciseO> exercises_;
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.logicserver.protobuf.ExerciseO> getExercisesList() {
    return exercises_;
  }
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.logicserver.protobuf.ExerciseOOrBuilder> 
      getExercisesOrBuilderList() {
    return exercises_;
  }
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  @java.lang.Override
  public int getExercisesCount() {
    return exercises_.size();
  }
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  @java.lang.Override
  public via.sep3.logicserver.protobuf.ExerciseO getExercises(int index) {
    return exercises_.get(index);
  }
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  @java.lang.Override
  public via.sep3.logicserver.protobuf.ExerciseOOrBuilder getExercisesOrBuilder(
      int index) {
    return exercises_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(2, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (durationInMin_ != 0) {
      output.writeInt32(5, durationInMin_);
    }
    if (createdBy_ != 0) {
      output.writeInt32(6, createdBy_);
    }
    if (followedBy_ != 0) {
      output.writeInt32(7, followedBy_);
    }
    if (isPublic_ != false) {
      output.writeBool(8, isPublic_);
    }
    for (int i = 0; i < exercises_.size(); i++) {
      output.writeMessage(9, exercises_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (durationInMin_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, durationInMin_);
    }
    if (createdBy_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, createdBy_);
    }
    if (followedBy_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, followedBy_);
    }
    if (isPublic_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isPublic_);
    }
    for (int i = 0; i < exercises_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, exercises_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.logicserver.protobuf.WorkoutO)) {
      return super.equals(obj);
    }
    via.sep3.logicserver.protobuf.WorkoutO other = (via.sep3.logicserver.protobuf.WorkoutO) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getDurationInMin()
        != other.getDurationInMin()) return false;
    if (getCreatedBy()
        != other.getCreatedBy()) return false;
    if (getFollowedBy()
        != other.getFollowedBy()) return false;
    if (getIsPublic()
        != other.getIsPublic()) return false;
    if (!getExercisesList()
        .equals(other.getExercisesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + DURATIONINMIN_FIELD_NUMBER;
    hash = (53 * hash) + getDurationInMin();
    hash = (37 * hash) + CREATEDBY_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedBy();
    hash = (37 * hash) + FOLLOWEDBY_FIELD_NUMBER;
    hash = (53 * hash) + getFollowedBy();
    hash = (37 * hash) + ISPUBLIC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsPublic());
    if (getExercisesCount() > 0) {
      hash = (37 * hash) + EXERCISES_FIELD_NUMBER;
      hash = (53 * hash) + getExercisesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.WorkoutO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.logicserver.protobuf.WorkoutO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WorkoutO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WorkoutO)
      via.sep3.logicserver.protobuf.WorkoutOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.logicserver.protobuf.WorkoutO.class, via.sep3.logicserver.protobuf.WorkoutO.Builder.class);
    }

    // Construct using via.sep3.logicserver.protobuf.WorkoutO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getExercisesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      description_ = "";

      durationInMin_ = 0;

      createdBy_ = 0;

      followedBy_ = 0;

      isPublic_ = false;

      if (exercisesBuilder_ == null) {
        exercises_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        exercisesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutO_descriptor;
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.WorkoutO getDefaultInstanceForType() {
      return via.sep3.logicserver.protobuf.WorkoutO.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.WorkoutO build() {
      via.sep3.logicserver.protobuf.WorkoutO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.WorkoutO buildPartial() {
      via.sep3.logicserver.protobuf.WorkoutO result = new via.sep3.logicserver.protobuf.WorkoutO(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.name_ = name_;
      result.description_ = description_;
      result.durationInMin_ = durationInMin_;
      result.createdBy_ = createdBy_;
      result.followedBy_ = followedBy_;
      result.isPublic_ = isPublic_;
      if (exercisesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          exercises_ = java.util.Collections.unmodifiableList(exercises_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.exercises_ = exercises_;
      } else {
        result.exercises_ = exercisesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.logicserver.protobuf.WorkoutO) {
        return mergeFrom((via.sep3.logicserver.protobuf.WorkoutO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.logicserver.protobuf.WorkoutO other) {
      if (other == via.sep3.logicserver.protobuf.WorkoutO.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getDurationInMin() != 0) {
        setDurationInMin(other.getDurationInMin());
      }
      if (other.getCreatedBy() != 0) {
        setCreatedBy(other.getCreatedBy());
      }
      if (other.getFollowedBy() != 0) {
        setFollowedBy(other.getFollowedBy());
      }
      if (other.getIsPublic() != false) {
        setIsPublic(other.getIsPublic());
      }
      if (exercisesBuilder_ == null) {
        if (!other.exercises_.isEmpty()) {
          if (exercises_.isEmpty()) {
            exercises_ = other.exercises_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureExercisesIsMutable();
            exercises_.addAll(other.exercises_);
          }
          onChanged();
        }
      } else {
        if (!other.exercises_.isEmpty()) {
          if (exercisesBuilder_.isEmpty()) {
            exercisesBuilder_.dispose();
            exercisesBuilder_ = null;
            exercises_ = other.exercises_;
            bitField0_ = (bitField0_ & ~0x00000001);
            exercisesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getExercisesFieldBuilder() : null;
          } else {
            exercisesBuilder_.addAllMessages(other.exercises_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.logicserver.protobuf.WorkoutO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.logicserver.protobuf.WorkoutO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private int durationInMin_ ;
    /**
     * <code>int32 durationInMin = 5;</code>
     * @return The durationInMin.
     */
    @java.lang.Override
    public int getDurationInMin() {
      return durationInMin_;
    }
    /**
     * <code>int32 durationInMin = 5;</code>
     * @param value The durationInMin to set.
     * @return This builder for chaining.
     */
    public Builder setDurationInMin(int value) {
      
      durationInMin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 durationInMin = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDurationInMin() {
      
      durationInMin_ = 0;
      onChanged();
      return this;
    }

    private int createdBy_ ;
    /**
     * <code>int32 createdBy = 6;</code>
     * @return The createdBy.
     */
    @java.lang.Override
    public int getCreatedBy() {
      return createdBy_;
    }
    /**
     * <code>int32 createdBy = 6;</code>
     * @param value The createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedBy(int value) {
      
      createdBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 createdBy = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedBy() {
      
      createdBy_ = 0;
      onChanged();
      return this;
    }

    private int followedBy_ ;
    /**
     * <code>int32 followedBy = 7;</code>
     * @return The followedBy.
     */
    @java.lang.Override
    public int getFollowedBy() {
      return followedBy_;
    }
    /**
     * <code>int32 followedBy = 7;</code>
     * @param value The followedBy to set.
     * @return This builder for chaining.
     */
    public Builder setFollowedBy(int value) {
      
      followedBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 followedBy = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFollowedBy() {
      
      followedBy_ = 0;
      onChanged();
      return this;
    }

    private boolean isPublic_ ;
    /**
     * <code>bool isPublic = 8;</code>
     * @return The isPublic.
     */
    @java.lang.Override
    public boolean getIsPublic() {
      return isPublic_;
    }
    /**
     * <code>bool isPublic = 8;</code>
     * @param value The isPublic to set.
     * @return This builder for chaining.
     */
    public Builder setIsPublic(boolean value) {
      
      isPublic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isPublic = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPublic() {
      
      isPublic_ = false;
      onChanged();
      return this;
    }

    private java.util.List<via.sep3.logicserver.protobuf.ExerciseO> exercises_ =
      java.util.Collections.emptyList();
    private void ensureExercisesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        exercises_ = new java.util.ArrayList<via.sep3.logicserver.protobuf.ExerciseO>(exercises_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.logicserver.protobuf.ExerciseO, via.sep3.logicserver.protobuf.ExerciseO.Builder, via.sep3.logicserver.protobuf.ExerciseOOrBuilder> exercisesBuilder_;

    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public java.util.List<via.sep3.logicserver.protobuf.ExerciseO> getExercisesList() {
      if (exercisesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(exercises_);
      } else {
        return exercisesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public int getExercisesCount() {
      if (exercisesBuilder_ == null) {
        return exercises_.size();
      } else {
        return exercisesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseO getExercises(int index) {
      if (exercisesBuilder_ == null) {
        return exercises_.get(index);
      } else {
        return exercisesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder setExercises(
        int index, via.sep3.logicserver.protobuf.ExerciseO value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.set(index, value);
        onChanged();
      } else {
        exercisesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder setExercises(
        int index, via.sep3.logicserver.protobuf.ExerciseO.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.set(index, builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder addExercises(via.sep3.logicserver.protobuf.ExerciseO value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.add(value);
        onChanged();
      } else {
        exercisesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder addExercises(
        int index, via.sep3.logicserver.protobuf.ExerciseO value) {
      if (exercisesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureExercisesIsMutable();
        exercises_.add(index, value);
        onChanged();
      } else {
        exercisesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder addExercises(
        via.sep3.logicserver.protobuf.ExerciseO.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.add(builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder addExercises(
        int index, via.sep3.logicserver.protobuf.ExerciseO.Builder builderForValue) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.add(index, builderForValue.build());
        onChanged();
      } else {
        exercisesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder addAllExercises(
        java.lang.Iterable<? extends via.sep3.logicserver.protobuf.ExerciseO> values) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, exercises_);
        onChanged();
      } else {
        exercisesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder clearExercises() {
      if (exercisesBuilder_ == null) {
        exercises_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        exercisesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public Builder removeExercises(int index) {
      if (exercisesBuilder_ == null) {
        ensureExercisesIsMutable();
        exercises_.remove(index);
        onChanged();
      } else {
        exercisesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseO.Builder getExercisesBuilder(
        int index) {
      return getExercisesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseOOrBuilder getExercisesOrBuilder(
        int index) {
      if (exercisesBuilder_ == null) {
        return exercises_.get(index);  } else {
        return exercisesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public java.util.List<? extends via.sep3.logicserver.protobuf.ExerciseOOrBuilder> 
         getExercisesOrBuilderList() {
      if (exercisesBuilder_ != null) {
        return exercisesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(exercises_);
      }
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseO.Builder addExercisesBuilder() {
      return getExercisesFieldBuilder().addBuilder(
          via.sep3.logicserver.protobuf.ExerciseO.getDefaultInstance());
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public via.sep3.logicserver.protobuf.ExerciseO.Builder addExercisesBuilder(
        int index) {
      return getExercisesFieldBuilder().addBuilder(
          index, via.sep3.logicserver.protobuf.ExerciseO.getDefaultInstance());
    }
    /**
     * <code>repeated .ExerciseO exercises = 9;</code>
     */
    public java.util.List<via.sep3.logicserver.protobuf.ExerciseO.Builder> 
         getExercisesBuilderList() {
      return getExercisesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.logicserver.protobuf.ExerciseO, via.sep3.logicserver.protobuf.ExerciseO.Builder, via.sep3.logicserver.protobuf.ExerciseOOrBuilder> 
        getExercisesFieldBuilder() {
      if (exercisesBuilder_ == null) {
        exercisesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sep3.logicserver.protobuf.ExerciseO, via.sep3.logicserver.protobuf.ExerciseO.Builder, via.sep3.logicserver.protobuf.ExerciseOOrBuilder>(
                exercises_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        exercises_ = null;
      }
      return exercisesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WorkoutO)
  }

  // @@protoc_insertion_point(class_scope:WorkoutO)
  private static final via.sep3.logicserver.protobuf.WorkoutO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.logicserver.protobuf.WorkoutO();
  }

  public static via.sep3.logicserver.protobuf.WorkoutO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkoutO>
      PARSER = new com.google.protobuf.AbstractParser<WorkoutO>() {
    @java.lang.Override
    public WorkoutO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WorkoutO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WorkoutO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkoutO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.logicserver.protobuf.WorkoutO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

