// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

public interface WorkoutOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 durationInMin = 5;</code>
   * @return The durationInMin.
   */
  int getDurationInMin();

  /**
   * <code>int32 createdBy = 6;</code>
   * @return The createdBy.
   */
  int getCreatedBy();

  /**
   * <code>int32 followedBy = 7;</code>
   * @return The followedBy.
   */
  int getFollowedBy();

  /**
   * <code>bool isPublic = 8;</code>
   * @return The isPublic.
   */
  boolean getIsPublic();

  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  java.util.List<via.sep3.logicserver.protobuf.ExerciseO> 
      getExercisesList();
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  via.sep3.logicserver.protobuf.ExerciseO getExercises(int index);
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  int getExercisesCount();
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  java.util.List<? extends via.sep3.logicserver.protobuf.ExerciseOOrBuilder> 
      getExercisesOrBuilderList();
  /**
   * <code>repeated .ExerciseO exercises = 9;</code>
   */
  via.sep3.logicserver.protobuf.ExerciseOOrBuilder getExercisesOrBuilder(
      int index);
}
