// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutService.proto

package via.sep3.logicserver.protobuf;

public interface WorkoutsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Workouts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .WorkoutObj workouts = 1;</code>
   */
  java.util.List<via.sep3.logicserver.protobuf.WorkoutObj> 
      getWorkoutsList();
  /**
   * <code>repeated .WorkoutObj workouts = 1;</code>
   */
  via.sep3.logicserver.protobuf.WorkoutObj getWorkouts(int index);
  /**
   * <code>repeated .WorkoutObj workouts = 1;</code>
   */
  int getWorkoutsCount();
  /**
   * <code>repeated .WorkoutObj workouts = 1;</code>
   */
  java.util.List<? extends via.sep3.logicserver.protobuf.WorkoutObjOrBuilder> 
      getWorkoutsOrBuilderList();
  /**
   * <code>repeated .WorkoutObj workouts = 1;</code>
   */
  via.sep3.logicserver.protobuf.WorkoutObjOrBuilder getWorkoutsOrBuilder(
      int index);
}
