// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutService.proto

package via.sep3.logicserver.protobuf;

public interface WorkoutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Workout)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 durationInMin = 4;</code>
   * @return The durationInMin.
   */
  int getDurationInMin();

  /**
   * <code>.MemberObj createdBy = 5;</code>
   * @return Whether the createdBy field is set.
   */
  boolean hasCreatedBy();
  /**
   * <code>.MemberObj createdBy = 5;</code>
   * @return The createdBy.
   */
  via.sep3.logicserver.protobuf.MemberObj getCreatedBy();
  /**
   * <code>.MemberObj createdBy = 5;</code>
   */
  via.sep3.logicserver.protobuf.MemberObjOrBuilder getCreatedByOrBuilder();

  /**
   * <code>int32 followedBy = 6;</code>
   * @return The followedBy.
   */
  int getFollowedBy();

  /**
   * <code>bool isPublic = 7;</code>
   * @return The isPublic.
   */
  boolean getIsPublic();

  /**
   * <code>repeated .ExerciseObj exercises = 8;</code>
   */
  java.util.List<via.sep3.logicserver.protobuf.ExerciseObj> 
      getExercisesList();
  /**
   * <code>repeated .ExerciseObj exercises = 8;</code>
   */
  via.sep3.logicserver.protobuf.ExerciseObj getExercises(int index);
  /**
   * <code>repeated .ExerciseObj exercises = 8;</code>
   */
  int getExercisesCount();
  /**
   * <code>repeated .ExerciseObj exercises = 8;</code>
   */
  java.util.List<? extends via.sep3.logicserver.protobuf.ExerciseObjOrBuilder> 
      getExercisesOrBuilderList();
  /**
   * <code>repeated .ExerciseObj exercises = 8;</code>
   */
  via.sep3.logicserver.protobuf.ExerciseObjOrBuilder getExercisesOrBuilder(
      int index);
}
