// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

/**
 * Protobuf type {@code WorkoutsTO}
 */
public final class WorkoutsTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WorkoutsTO)
    WorkoutsTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkoutsTO.newBuilder() to construct.
  private WorkoutsTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkoutsTO() {
    workouts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorkoutsTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WorkoutsTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              workouts_ = new java.util.ArrayList<via.sep3.logicserver.protobuf.WorkoutO>();
              mutable_bitField0_ |= 0x00000001;
            }
            workouts_.add(
                input.readMessage(via.sep3.logicserver.protobuf.WorkoutO.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        workouts_ = java.util.Collections.unmodifiableList(workouts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutsTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutsTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.logicserver.protobuf.WorkoutsTO.class, via.sep3.logicserver.protobuf.WorkoutsTO.Builder.class);
  }

  public static final int WORKOUTS_FIELD_NUMBER = 1;
  private java.util.List<via.sep3.logicserver.protobuf.WorkoutO> workouts_;
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<via.sep3.logicserver.protobuf.WorkoutO> getWorkoutsList() {
    return workouts_;
  }
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sep3.logicserver.protobuf.WorkoutOOrBuilder> 
      getWorkoutsOrBuilderList() {
    return workouts_;
  }
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  @java.lang.Override
  public int getWorkoutsCount() {
    return workouts_.size();
  }
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  @java.lang.Override
  public via.sep3.logicserver.protobuf.WorkoutO getWorkouts(int index) {
    return workouts_.get(index);
  }
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  @java.lang.Override
  public via.sep3.logicserver.protobuf.WorkoutOOrBuilder getWorkoutsOrBuilder(
      int index) {
    return workouts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < workouts_.size(); i++) {
      output.writeMessage(1, workouts_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < workouts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, workouts_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.logicserver.protobuf.WorkoutsTO)) {
      return super.equals(obj);
    }
    via.sep3.logicserver.protobuf.WorkoutsTO other = (via.sep3.logicserver.protobuf.WorkoutsTO) obj;

    if (!getWorkoutsList()
        .equals(other.getWorkoutsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWorkoutsCount() > 0) {
      hash = (37 * hash) + WORKOUTS_FIELD_NUMBER;
      hash = (53 * hash) + getWorkoutsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.logicserver.protobuf.WorkoutsTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.logicserver.protobuf.WorkoutsTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WorkoutsTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WorkoutsTO)
      via.sep3.logicserver.protobuf.WorkoutsTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutsTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutsTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.logicserver.protobuf.WorkoutsTO.class, via.sep3.logicserver.protobuf.WorkoutsTO.Builder.class);
    }

    // Construct using via.sep3.logicserver.protobuf.WorkoutsTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getWorkoutsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (workoutsBuilder_ == null) {
        workouts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        workoutsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.logicserver.protobuf.LogicServerOuterClass.internal_static_WorkoutsTO_descriptor;
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.WorkoutsTO getDefaultInstanceForType() {
      return via.sep3.logicserver.protobuf.WorkoutsTO.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.WorkoutsTO build() {
      via.sep3.logicserver.protobuf.WorkoutsTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.logicserver.protobuf.WorkoutsTO buildPartial() {
      via.sep3.logicserver.protobuf.WorkoutsTO result = new via.sep3.logicserver.protobuf.WorkoutsTO(this);
      int from_bitField0_ = bitField0_;
      if (workoutsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          workouts_ = java.util.Collections.unmodifiableList(workouts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.workouts_ = workouts_;
      } else {
        result.workouts_ = workoutsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.logicserver.protobuf.WorkoutsTO) {
        return mergeFrom((via.sep3.logicserver.protobuf.WorkoutsTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.logicserver.protobuf.WorkoutsTO other) {
      if (other == via.sep3.logicserver.protobuf.WorkoutsTO.getDefaultInstance()) return this;
      if (workoutsBuilder_ == null) {
        if (!other.workouts_.isEmpty()) {
          if (workouts_.isEmpty()) {
            workouts_ = other.workouts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWorkoutsIsMutable();
            workouts_.addAll(other.workouts_);
          }
          onChanged();
        }
      } else {
        if (!other.workouts_.isEmpty()) {
          if (workoutsBuilder_.isEmpty()) {
            workoutsBuilder_.dispose();
            workoutsBuilder_ = null;
            workouts_ = other.workouts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            workoutsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getWorkoutsFieldBuilder() : null;
          } else {
            workoutsBuilder_.addAllMessages(other.workouts_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.logicserver.protobuf.WorkoutsTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.logicserver.protobuf.WorkoutsTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sep3.logicserver.protobuf.WorkoutO> workouts_ =
      java.util.Collections.emptyList();
    private void ensureWorkoutsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        workouts_ = new java.util.ArrayList<via.sep3.logicserver.protobuf.WorkoutO>(workouts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.logicserver.protobuf.WorkoutO, via.sep3.logicserver.protobuf.WorkoutO.Builder, via.sep3.logicserver.protobuf.WorkoutOOrBuilder> workoutsBuilder_;

    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public java.util.List<via.sep3.logicserver.protobuf.WorkoutO> getWorkoutsList() {
      if (workoutsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(workouts_);
      } else {
        return workoutsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public int getWorkoutsCount() {
      if (workoutsBuilder_ == null) {
        return workouts_.size();
      } else {
        return workoutsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public via.sep3.logicserver.protobuf.WorkoutO getWorkouts(int index) {
      if (workoutsBuilder_ == null) {
        return workouts_.get(index);
      } else {
        return workoutsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder setWorkouts(
        int index, via.sep3.logicserver.protobuf.WorkoutO value) {
      if (workoutsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorkoutsIsMutable();
        workouts_.set(index, value);
        onChanged();
      } else {
        workoutsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder setWorkouts(
        int index, via.sep3.logicserver.protobuf.WorkoutO.Builder builderForValue) {
      if (workoutsBuilder_ == null) {
        ensureWorkoutsIsMutable();
        workouts_.set(index, builderForValue.build());
        onChanged();
      } else {
        workoutsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder addWorkouts(via.sep3.logicserver.protobuf.WorkoutO value) {
      if (workoutsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorkoutsIsMutable();
        workouts_.add(value);
        onChanged();
      } else {
        workoutsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder addWorkouts(
        int index, via.sep3.logicserver.protobuf.WorkoutO value) {
      if (workoutsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureWorkoutsIsMutable();
        workouts_.add(index, value);
        onChanged();
      } else {
        workoutsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder addWorkouts(
        via.sep3.logicserver.protobuf.WorkoutO.Builder builderForValue) {
      if (workoutsBuilder_ == null) {
        ensureWorkoutsIsMutable();
        workouts_.add(builderForValue.build());
        onChanged();
      } else {
        workoutsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder addWorkouts(
        int index, via.sep3.logicserver.protobuf.WorkoutO.Builder builderForValue) {
      if (workoutsBuilder_ == null) {
        ensureWorkoutsIsMutable();
        workouts_.add(index, builderForValue.build());
        onChanged();
      } else {
        workoutsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder addAllWorkouts(
        java.lang.Iterable<? extends via.sep3.logicserver.protobuf.WorkoutO> values) {
      if (workoutsBuilder_ == null) {
        ensureWorkoutsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, workouts_);
        onChanged();
      } else {
        workoutsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder clearWorkouts() {
      if (workoutsBuilder_ == null) {
        workouts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        workoutsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public Builder removeWorkouts(int index) {
      if (workoutsBuilder_ == null) {
        ensureWorkoutsIsMutable();
        workouts_.remove(index);
        onChanged();
      } else {
        workoutsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public via.sep3.logicserver.protobuf.WorkoutO.Builder getWorkoutsBuilder(
        int index) {
      return getWorkoutsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public via.sep3.logicserver.protobuf.WorkoutOOrBuilder getWorkoutsOrBuilder(
        int index) {
      if (workoutsBuilder_ == null) {
        return workouts_.get(index);  } else {
        return workoutsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public java.util.List<? extends via.sep3.logicserver.protobuf.WorkoutOOrBuilder> 
         getWorkoutsOrBuilderList() {
      if (workoutsBuilder_ != null) {
        return workoutsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(workouts_);
      }
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public via.sep3.logicserver.protobuf.WorkoutO.Builder addWorkoutsBuilder() {
      return getWorkoutsFieldBuilder().addBuilder(
          via.sep3.logicserver.protobuf.WorkoutO.getDefaultInstance());
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public via.sep3.logicserver.protobuf.WorkoutO.Builder addWorkoutsBuilder(
        int index) {
      return getWorkoutsFieldBuilder().addBuilder(
          index, via.sep3.logicserver.protobuf.WorkoutO.getDefaultInstance());
    }
    /**
     * <code>repeated .WorkoutO workouts = 1;</code>
     */
    public java.util.List<via.sep3.logicserver.protobuf.WorkoutO.Builder> 
         getWorkoutsBuilderList() {
      return getWorkoutsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sep3.logicserver.protobuf.WorkoutO, via.sep3.logicserver.protobuf.WorkoutO.Builder, via.sep3.logicserver.protobuf.WorkoutOOrBuilder> 
        getWorkoutsFieldBuilder() {
      if (workoutsBuilder_ == null) {
        workoutsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sep3.logicserver.protobuf.WorkoutO, via.sep3.logicserver.protobuf.WorkoutO.Builder, via.sep3.logicserver.protobuf.WorkoutOOrBuilder>(
                workouts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        workouts_ = null;
      }
      return workoutsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WorkoutsTO)
  }

  // @@protoc_insertion_point(class_scope:WorkoutsTO)
  private static final via.sep3.logicserver.protobuf.WorkoutsTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.logicserver.protobuf.WorkoutsTO();
  }

  public static via.sep3.logicserver.protobuf.WorkoutsTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkoutsTO>
      PARSER = new com.google.protobuf.AbstractParser<WorkoutsTO>() {
    @java.lang.Override
    public WorkoutsTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WorkoutsTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WorkoutsTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkoutsTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.logicserver.protobuf.WorkoutsTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

