// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

public interface WorkoutsTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutsTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  java.util.List<via.sep3.logicserver.protobuf.WorkoutO> 
      getWorkoutsList();
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  via.sep3.logicserver.protobuf.WorkoutO getWorkouts(int index);
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  int getWorkoutsCount();
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  java.util.List<? extends via.sep3.logicserver.protobuf.WorkoutOOrBuilder> 
      getWorkoutsOrBuilderList();
  /**
   * <code>repeated .WorkoutO workouts = 1;</code>
   */
  via.sep3.logicserver.protobuf.WorkoutOOrBuilder getWorkoutsOrBuilder(
      int index);
}
