// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicServer.proto

package via.sep3.logicserver.protobuf;

public interface WorkoutIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 3;</code>
   * @return The id.
   */
  int getId();
}
